In [2]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import os

In [3]:
## Resize the image.
def resize(image):
    return cv2.resize(image,(129,129))


In [4]:
def shape(image):
    height = image.shape[0]
    width = image.shape[1]
    return height,width

In [8]:
path = "/home/mononoke/ChessDetection/IIIT-A/FaceRecongnition/images1/Training images"

In [15]:
images = os.listdir(path)

In [23]:
for i in images:
    image = cv2.imread(os.path.join(path,i))
    # cv2.imshow()

[[[127 127 127]
  [ 45  45  45]
  [ 55  55  55]
  ...
  [ 49  49  49]
  [ 49  49  49]
  [ 46  46  46]]

 [[130 130 130]
  [ 49  49  49]
  [ 55  55  55]
  ...
  [ 46  46  46]
  [ 48  48  48]
  [ 48  48  48]]

 [[128 128 128]
  [ 51  51  51]
  [ 53  53  53]
  ...
  [ 43  43  43]
  [ 47  47  47]
  [ 50  50  50]]

 ...

 [[199 199 199]
  [193 193 193]
  [189 189 189]
  ...
  [162 162 162]
  [173 173 173]
  [196 196 196]]

 [[198 198 198]
  [194 194 194]
  [192 192 192]
  ...
  [161 161 161]
  [161 161 161]
  [174 174 174]]

 [[191 191 191]
  [192 192 192]
  [194 194 194]
  ...
  [169 169 169]
  [161 161 161]
  [161 161 161]]]
[[[ 45  45  45]
  [ 35  35  35]
  [ 34  34  34]
  ...
  [228 228 228]
  [224 224 224]
  [221 221 221]]

 [[ 59  59  59]
  [ 43  43  43]
  [ 39  39  39]
  ...
  [216 216 216]
  [220 220 220]
  [230 230 230]]

 [[ 67  67  67]
  [ 42  42  42]
  [ 35  35  35]
  ...
  [224 224 224]
  [222 222 222]
  [224 224 224]]

 ...

 [[223 223 223]
  [223 223 223]
  [222 222 222]
  ..